const imgs = {
    logo: require('./imgs/Logo2.png'),
    forgetPass:require('./imgs/ForgetPass.png'),
    OTP_Vetitification : require('./imgs/OTP.png'),
    logo2 : require('./imgs/CP.png'), 
    orderdone:require('./imgs/orderdone.png'),

    golodOffer : require('./imgs/goldOffer.png'), 
    silveroffer:require('./imgs/silveroffer.png'),
    starterOffer:require('./imgs/starterOffer.png'),
    checkedIcon : require('./imgs/check-circle.png'),
    subtract : require('./imgs/Subtract.png'),
    emailIcon : require('./imgs/emailIcon.png'), 
    phonIcon : require('./imgs/phonIcon.png'),
    edit : require('./imgs/Edit.png'),
    profession : require('./imgs/profession.png'), 
    currancy : require('./imgs/cyrrancy.png'),
    drawer : require('./imgs/Drawer.png'), 
    userIcon : require('./imgs/userIcon.png'), 
    outOfCridite : require('./imgs/outOfCridite.png'), 
    onBoarding3 : require('./imgs/onBoarding3.png'),
    onBoarding2 : require('./imgs/onBoarding2.png'),
    onBoarding1 : require('./imgs/onBoarding1.png'),
    frame1 : require('./imgs/Frame1.png'),
    frame2 : require('./imgs/Frame2.png'),
    balance_icon:require('./imgs/balance_icon.png'),
    changePassword:require('./imgs/changePassword.png'),
    brandprimary:require('./imgs/brandprimary.png'),
    userPrimary:require('./imgs/userPrimary.png'),
    homePrimary:require('./imgs/subtractPrimary.png'),
    walletPrimary:require('./imgs/walletPrimamry.png'),

    brand:require('./imgs/brand.png'),
    user:require('./imgs/user.png'),
    home:require('./imgs/home.png'),
    wallet:require('./imgs/wallet.png'),
}

export default imgs;